modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/dawnflyc/HeavenEarthRing/issues"

[[mods]]
modId="heavenearthring"
version="${file.jarVersion}"
displayName="Heaven Earth Ring"
displayURL="https://github.com/dawnflyc/HeavenEarthRing"
logoFile="heavenearthring.png"
credits=""
authors="YD Team"
description='''
'''
[[dependencies.heavenearthring]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.heavenearthring]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
